version: '3'

networks:
    # A network for the laravel containers
    laravel:

services:

    # Nginx web server
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-dev
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        container_name: mysql-dev
        restart: unless-stopped
        tty: true
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile.app
        container_name: php-dev
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel